#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jun 20, 2019 08:34:04 PM CST  platform: Windows NT

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import pydice_support
from os import path


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = PyDice(root)
    pydice_support.init(root, top)
    root.mainloop()


w = None


def create_PyDice(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = PyDice(w)
    pydice_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_PyDice():
    global w
    w.destroy()
    w = None


class PyDice:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font9 = "-family 宋体 -size 16 -weight bold -slant roman " \
                "-underline 0 -overstrike 0"

        top.geometry("611x522+566+174")
        top.title("PyDice")
        top.configure(background="#c0c4c3")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        # disable window resize
        top.resizable(0, 0)
        # set custom icon file
        if path.exists('./favicon.ico'):
            top.iconbitmap("./favicon.ico")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.0, rely=0.0, relheight=0.657, relwidth=1.003)
        self.Canvas1.configure(background="#8076a3")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(highlightthickness="0")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=613)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.0, rely=0.661, height=83, width=618)
        self.Label1.configure(activebackground="#c0c4c3")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c0c4c3")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''... ...''')
        self.Label1.configure(width=618)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.426, rely=0.843, height=38, width=99)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#c0c4c3")
        self.Button1.configure(command=pydice_support.start_rolling)
        self.Button1.configure(cursor="star")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Start''')
        self.Button1.configure(width=99)

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.sub_menu = tk.Menu(top, tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                                 activebackground="#ececec",
                                 activeforeground="#000000",
                                 background="#d9d9d9",
                                 font="TkMenuFont",
                                 foreground="#000000",
                                 label="File")
        self.sub_menu.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=pydice_support.load_from_img_folder,
            font="TkMenuFont",
            foreground="#000000",
            label="From image folder...")
        self.sub_menu.add_separator(
            background="#d9d9d9")
        self.sub_menu.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=pydice_support.quit_app,
            font="TkMenuFont",
            foreground="#000000",
            label="Quit")
        self.sub_menu1 = tk.Menu(top, tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                                 activebackground="#ececec",
                                 activeforeground="#000000",
                                 background="#d9d9d9",
                                 font="TkMenuFont",
                                 foreground="#000000",
                                 label="Help")
        self.sub_menu1.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=pydice_support.show_about_window,
            font="TkMenuFont",
            foreground="#000000",
            label="About")


if __name__ == '__main__':
    vp_start_gui()
