#############################################################################
# Generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#  Jun 20, 2019 08:34:01 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family 宋体 -size 16 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background {#c0c4c3} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 611x522+566+174
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1041
    wm minsize $top 611 432
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "PyDice"
    vTcl:DefineAlias "$top" "PyDice" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can43 \
        -background {#8076a3} -height 343 -highlightbackground {#d9d9d9} \
        -highlightcolor black -highlightthickness 0 -insertbackground black \
        -relief ridge -selectbackground {#c4c4c4} -selectforeground black \
        -width 613 
    vTcl:DefineAlias "$top.can43" "Canvas1" vTcl:WidgetProc "PyDice" 1
    label $top.lab44 \
        -activebackground {#c0c4c3} -activeforeground black \
        -background {#c0c4c3} -borderwidth 2 -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {... ...} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "PyDice" 1
    button $top.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#c0c4c3} -command start_rolling -cursor star \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Start 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "PyDice" 1
    set site_3_0 $top.m46
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men47" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File 
    menu $site_3_0.men47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Microsoft YaHei UI} 9} \
        -foreground black -tearoff 0 
    $site_3_0.men47 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#load_from_img_folder} \
        -font TkMenuFont -foreground {#000000} -label {From image folder...} 
    $site_3_0.men47 add separator \
        -background {#d9d9d9} 
    $site_3_0.men47 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#quit_app} -font TkMenuFont \
        -foreground {#000000} -label Quit 
    $site_3_0 add cascade \
        -menu "$site_3_0.men47" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File -menu "$site_3_0.men49" \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label Help 
    menu $site_3_0.men49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Microsoft YaHei UI} 9} \
        -foreground black -tearoff 0 
    $site_3_0.men49 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#show_about_window} -font TkMenuFont \
        -foreground {#000000} -label About 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can43 \
        -in $top -x 0 -y 0 -width 613 -relwidth 0 -height 343 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 0 -y 348 -width 618 -relwidth 0 -height 83 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 260 -y 440 -width 99 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

